swagger: '2.0'
info:
  title: Bank Argent Transactions API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /account/{id}/transactions:
    get:
      tags:
        - Transactions Module
      summary: Get all transactions for a account
      description: return all transactions
  /transactions/{id}:
    get:
      tags:
        - Transactions Module
      summary: Get a transaction base on id
      description: return a single Transaction
      parameters:
        - in: id
          name: id
          description: Transaction Id
          required: true
          schema:
            $ref: '#/definitions/Transaction'
    post:
      tags:
        - Transactions Module
      summary: Add a new transaction
      description: API for Transaction
      parameters:
        - in: id
          name: id
          description: Transaction Id
          required: true
          schema:
            $ref: '#/definitions/Transaction'
    put:
      tags:
        - Transactions Module
      summary: Update a transaction base on id
      description: API for Transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
    delete:
      tags:
        - Transactions Module
      summary: Delete a transaction base on id
      description: API for Transaction
  /accounts/:
    get:
      tags:
        - Account Module
      summary: Get all account
      description: API for Account
  /accounts/id:
    get:
      tags:
        - Account Module
      summary: Get a account base on id
      description: API for Account
      parameters:
        - in: id
          name: id
          description: Account Id
          required: true
          schema:
            $ref: '#/definitions/Account'
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Account:
    properties:
      id:
        type: int
        description: account id
      transactions:
        type: array
        description: array of transaction id
      title:
        type: string
        description: transactions title
      balance:
        type: string
        description: transactions balance
  Transaction:
    properties:
      id:
        type: integer
        description: transaction id
      date:
        type: string
        description: transaction date
      description:
        type: string
        description: transaction description
      amount:
        type: integer
        description: transaction amount
      type:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: transaction notes

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
