swagger: '2.0'
info:
  title: Bank Argent Transactions API documentation
  description: Contains all available API endpoints in this codebase
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /bank-accounts/{id}/transactions:
    get:
      tags:
        - Transactions Module
      summary: Get all transactions of a month for a account
      description: return all transactions for a user with a specified month
      parameters:
        - in: path
          name: id
          description: the account Id
          required: true
          type: string
        - in: query
          name: month
          required: false
          type: string
          description: Month Id
      responses:
        '200':
          description: OK - All transactions of the user retrieved successully
          schema:
            type: array
            items:
              $ref: '#/definitions/TransactionModel'
        '404':
          description: Not Found - The requested resources was not found in this server
        '500':
          description: Internal Server Error
  /transactions/{id}:
    parameters:
      - in: path
        name: id
        description: Transaction Id
        required: true
        type: integer
    get:
      tags:
        - Transactions Module
      summary: Get a transaction base on id
      description: return a single Transaction
      responses:
        '200':
          description: OK - All transactions of the user retrieved successully
          schema:
            $ref: '#/definitions/TransactionModel'
        '404':
          description: Not Found - The requested resources was not found in this server
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions Module
      summary: Update a transaction base on id
      description: API for Transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: integer
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionRequest'
      responses:
        '200':
          description: All transactions of the user retrieved successully
          schema:
            $ref: '#/definitions/TransactionModel'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '404':
          description: Not Found - The requested resources was not found in this server
        '500':
          description: Internal Server Error
      produces:
        - application/json
  /bank-accounts/:
    get:
      tags:
        - BankAccounts Module
      summary: Get all account
      description: API for Account
      responses:
        '200':
          description: OK - All accounts retrieved successully
          schema:
            type: array
            items:
              $ref: '#/definitions/BankAccountModel'
        '404':
          description: Not Found - The requested resources was not found in this server
        '500':
          description: Internal Server Error
  /bank-accounts/{id}:
    get:
      tags:
        - BankAccounts Module
      summary: Get a account base on id
      description: API for BankAccounts
      parameters:
        - in: path
          name: id
          description: BankAccount Id
          required: true
          type: integer
      responses:
        '200':
          description: OK - Account retrieved successully
          schema:
            $ref: '#/definitions/BankAccountModel'
        '404':
          description: Not Found - The requested resources was not found in this server
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  BankAccountRequest:
    properties:
      id:
        type: integer
        description: account id
  TransactionModel:
    properties:
      date:
        type: object
        pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
        example: '2019-05-17'
      category:
        type: string
      note:
        type: string
      type:
        type: string
      description:
        type: string
      amount:
        type: integer
        example: 1000
      balance:
        type: integer
        example: 2000
  TransactionRequest:
    properties:
      category:
        type: string
        description: transaction category
      note:
        type: string
        description: transaction note
  BankAccountModel:
    properties:
      id:
        type: integer
        description: account id
      bankAccount:
        type: string
        example: 'Argent Bank Credit Card'
        description: bank title
      balanceTitle:
        type: string
        example: 'Current balance'
        description: bank balance
      balanceValue:
        type: integer
        example: 1000
        description: bank balance
